### ISSUE TITLE
No Logs

### ISSUE THREAD

**Issue by peter-fritchley** [wa0x6e/ResqueBoard#20]
I dont have any logs showing up, and the real-time chart in the middle of the page never shows any activity, even though I can see from the status in the top right corner that the cube server is running.

I've gone to the URL of the emitter and collector in the browser, and i get the dashboard for each.

I've tried to post data into the collector using the example here: https://github.com/square/cube/wiki/Collector but nothing shows up in the cube dashboard.

I've gone into mongo directly and the data is in there - the check_events collection for instance has lots of data in it, and yet these aren't showing up in resqueboard.

Thanks.

**Comment by wa0x6e** [comment]
I'll look into it.

My guess is it happens when you're not in the same timezone as your webserver. Is that your case ?

**Comment by peter-fritchley** [comment]
The Php timezone is "Europe/London", not sure what the timezone in cube is set to, nor how I can change it.

Thanks for your help.

**Comment by kallealberg** [comment]
Got the same issue, trying to get the timezones sorted.

@peter-fritchley Cube does not support multiple timezones (UTC only) according to this: https://github.com/square/cube/issues/61

**Comment by wa0x6e** [comment]
Is your computer/browser on the same timezone than the server ?

**Comment by kallealberg** [comment]
Nope, theres a hour difference.
Servers are located in Ireland(UTC timezone) and i live in Sweden.

**Comment by wa0x6e** [comment]
I'll take a look

**Comment by peter-fritchley** [comment]
In my case, the server timezone matches the browser one.

Thanks.

**Comment by wa0x6e** [comment]
Seems like the timezone was missing from all logs data, and all dates inside Cube are considered to be UTC.

A fix was just pushed to Monolog repo, I'm working on a little patch to migrate all dates from UTC to your timezone.

**Comment by kallealberg** [comment]
Great!

**Comment by wa0x6e** [comment]
Can you confirm that when you're in the jobs view, the dates are all offset by your timezone ?

**Comment by wa0x6e** [comment]
The fix was merged into Monolog, but there's no ETA for the 1.6.1 release. If you want to the fix right now, you should edit the composer dependency to use the master.

In addition, a timezonefix.php script was added in the tools folder. Run it in the shell via `php -q tools/timezonfix.php apply`. It can take time, depending on the number of jobs.

I recommend you to update the database, and run it at night, when the traffic and server load is low, as it's overloading the mongo server with update queries.

**Apply the fix only when you update to Monolog > 1.6.0, or the latest master**

The fix is not needed if your server is on UTC.

**Comment by kallealberg** [comment]
I'll check it out!

**Comment by wa0x6e** [comment]
I'll close it for now, as it should be working if you have Monolog > 1.6.0.
